language: ruby
rvm:
  - 2.1.6

env:
  - CI=true

before_install:
  - PWD=`pwd`
  - "echo '## Installing dependencies'"
  - "sudo apt-get update"
  - "sudo apt-get install -y openssl build-essential xorg libssl-dev xfonts-75dpi"
  - "echo '## Downloading wkhtmltopdf'"
  - "wget http://download.gna.org/wkhtmltopdf/0.12/0.12.2.1/wkhtmltox-0.12.2.1_linux-wheezy-amd64.deb"
  - "echo '## Installing wkhtmltox'"
  - "sudo dpkg -i wkhtmltox-0.12.2.1_linux-wheezy-amd64.deb"
  - WHICH_WK=`which wkhtmltopdf`
  - "export WKHTMLTOPDF_CMD=$WHICH_WK"
